### ISSUE TITLE
Gradebook builder returns no data

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-gradereport_gradebook_builder#15]
I get the following error when clicking on the gradebook builder.

```
Error 324 (net::ERR_EMPTY_RESPONSE): The server closed the connection without sending any data.
```

**Comment by rrusso** [comment]
Looks like it might be a server issue. Trying to figure out WTF.

**Comment by philcali** [comment]
Master works fine for me.

Check your sub module.
On Apr 26, 2012 7:54 AM, "Robert Russo" <
reply@reply.github.com>
wrote:

**Comment by rrusso** [comment]
Re-checking out Moodle 22 in it's entirety.
