### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-gradereport_gradebook_builder#2]
I know it's early, but it's eating the page theme and is throwing these:

Invalid get_string() identifier: 'save_user' or component 'gradereport_builder_template'. Perhaps you are missing $string['save_user'] = ''; in /var/www/rrusso/22/grade/report/builder_template/lang/en/gradereport_builder_template.php?
line 6367 of /lib/moodlelib.php: call to debugging()
line 6959 of /lib/moodlelib.php: call to core_string_manager->get_string()
line 263 of /grade/report/gradebook_builder/lib.php: call to get_string()
line 266 of /grade/report/gradebook_builder/lib.php: call to {closure}()
line 179 of /grade/report/gradebook_builder/lib.php: call to grade_report_gradebook_builder->get_save_options()
line 49 of /grade/report/gradebook_builder/index.php: call to grade_report_gradebook_builder->output()
Invalid get_string() identifier: 'save_category' or component 'gradereport_builder_template'. Perhaps you are missing $string['save_category'] = ''; in /var/www/rrusso/22/grade/report/builder_template/lang/en/gradereport_builder_template.php?
line 6367 of /lib/moodlelib.php: call to debugging()
line 6959 of /lib/moodlelib.php: call to core_string_manager->get_string()
line 263 of /grade/report/gradebook_builder/lib.php: call to get_string()
line 271 of /grade/report/gradebook_builder/lib.php: call to {closure}()
line 179 of /grade/report/gradebook_builder/lib.php: call to grade_report_gradebook_builder->get_save_options()
line 49 of /grade/report/gradebook_builder/index.php: call to grade_report_gradebook_builder->output()
Invalid get_string() identifier: 'save_system' or component 'gradereport_builder_template'. Perhaps you are missing $string['save_system'] = ''; in /var/www/rrusso/22/grade/report/builder_template/lang/en/gradereport_builder_template.php?
line 6367 of /lib/moodlelib.php: call to debugging()
line 6959 of /lib/moodlelib.php: call to core_string_manager->get_string()
line 263 of /grade/report/gradebook_builder/lib.php: call to get_string()
line 276 of /grade/report/gradebook_builder/lib.php: call to {closure}()
line 179 of /grade/report/gradebook_builder/lib.php: call to grade_report_gradebook_builder->get_save_options()
line 49 of /grade/report/gradebook_builder/index.php: call to grade_report_gradebook_builder->output()

**Comment by adamzap** [comment]
Yeah, it's not ready for testing yet.

We should have it ready for you tomorrow to redo the CSS.

Just about everything is done except the template parts.

**Comment by rrusso** [comment]
Okiedokie.
