### ISSUE TITLE
CSS Rewrite

### ISSUE THREAD

**Issue by adamzap** [lsuits/lsu-gradereport_gradebook_builder#3]
Robert, we're ready for you to redo the CSS for the Gradebook Builder.

Remove `bootstrap.css` and my customizations in `app.css` and style the HTML in `templates/index.tpl`.

You'll need to maintain the `display: none` styles on certain elements from `app.css`.

**Comment by rrusso** [comment]
It's not ready for this yet. See issue #6

**Comment by rrusso** [comment]
That's a 4000 line css file that has practically nothing to do with the page.

I cannot include that at all into Moodle as it can break stuff.

**Comment by adamzap** [comment]
I'm not asking that we include it. I'm saying that it should be removed. Your CSS will replace what `bootstrap.css` is doing.

It was a placeholder so I could quickly get the initial design and javascript of the page done for the demo.

Also, most of these issues you are creating are legitimate, but we were intentionally waiting to do some of the more complex features until the CSS was done in case the markup needed to change (though it shouldn't).

**Comment by rrusso** [comment]
derp.

**Comment by rrusso** [comment]
Working on this now.

**Comment by rrusso** [comment]
Initial pass done and in master.
