### ISSUE TITLE
Template issues

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-gradereport_gradebook_builder#6]
Please be sure to use the LSU theme when doing all development work.

There are massive template issues in the gradebook builder beyond the scope of "theme matching" needed to be done.

Please checkout the latest codebase and work off the LSU theme for a quick overview of the issue.

**Comment by adamzap** [comment]
That's because `bootstrap.css` is still being included. That needs to be replaced with whatever CSS you want to use in production.

That was a placeholder I used during the design process.

**Comment by adamzap** [comment]
See #3

**Comment by rrusso** [comment]
Closing due to redundancy.
