### ISSUE TITLE
Singular / plural naming not implemented

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-gradereport_gradebook_builder#8]
as per the discussed the design specifications, when an instructor names a category tests and adds ten items, they should be called test 1, test 2, test 3, etc.

Currently they are called tests 1, test 1, etc.

Instead of having the administratively customizable plural / singular pairing as discussed, the system copies the name of the category and adds the number 1 without incrementing.

**Comment by adamzap** [comment]
I think this would be too complex to implement.

Where would the customization take place? At the course level or the system level?

**Comment by rrusso** [comment]
What about the incrementing of names and the ability for instructors to override the names assumed by the system?

**Comment by rrusso** [comment]
Before removing features, we should have a discussion regarding the difficulty / importance of said feature.

**Comment by adamzap** [comment]
I'll talk it over with @philcali, I may be misunderstanding.

The ROI of this feature seems pretty low to me.

**Comment by rrusso** [comment]
We absolutely need the system to increment when adding items.

Currently if you add five items to a category called Quizzes, you get the following.
- Quizzes
  - Quizzes 1
  - Quizzes 1
  - Quizzes 1
  - Quizzes 1
  - Quizzes 1

This is not helpful.

**Comment by adamzap** [comment]
Incrementing item names worked fine when I pushed it, pluralization didn't though.

**Comment by rrusso** [comment]
It increments if you add a second item. Adding 15 via the UI does not auto increment.

**Comment by philcali** [comment]
Fixes the auto-incrementing names (Quiz 1, Quiz 2, Quiz 3, etc): https://github.com/lsuits/gradebook_builder/commit/df1799b8bdca2993d2aaf7013423475ecada9b19

**Comment by rrusso** [comment]
Incrementing looks good.

What about all the singular / plural stuff we talked about?

**Comment by adamzap** [comment]
What is the UI for that? If they are able to enter arbitrary category names, I don't see an admin-populated pluralization solution being scalable.

What about when a Spanish instructor wants to call a category "exámenes"? And when a German instructor wants to call a category "Prüfungen"? How will it deal with multiple-word category names?

**Comment by rrusso** [comment]
The admin UI is quite simple.

PLURAL                                        SINGULAR
Terms                                           Term
Exámenes                                     Exámen
Graded exercises                           Graded exercise

Initially we could build this up with data extracted from production 1.9 and we have a large enough dataset to get a good head-start.

This UI would add to the ones existing in the system. Existing ones would then be collapsed (editable when expanded) to not take up real estate.

**Comment by philcali** [comment]
Rright, I don't see how that will scale. I think plainly incrementing the numbers like we have it is a good solution, or if that's a bit confusing, we could do something like: "Category Name Item #number" ex: "Exams Item #1" for a category called "Exams". That might be a bit verbose for simple gradebook building, though.

**Comment by rrusso** [comment]
If there was no match, it would simply re-use the plural as input.
